services:
  - type: web
    name: pairlet-ws
    env: node
    buildCommand: npm install
    startCommand: npm run ws
    envVars:
      - key: PORT
        value: 10000
      - key: WS_PORT
        value: 10000
